### ISSUE TITLE
Problem following readme instructions

### ISSUE THREAD

**Issue by emhoracek** [positiondev/offset#15]
Trying to install, I ran into trouble here:

```
curl http://localhost:5555/wp-json/wp/v2/ | jq
```

If got only this message: 

```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    93    0    93    0     0    719      0 --:--:-- --:--:-- --:--:--   715
[
  {
    "code": "json_no_route",
    "message": "No route was found matching the URL and request method"
  }
]
```

Is this because you switched back to v1 and the URL is different?

**Comment by dbp** [comment]
I think that's because I switched it back to v1 of the api, and forgot to update that. Could you try doing that curl command without the `/wp/v2/`? That suffix was added for v2 of the api.

**Comment by emhoracek** [comment]
Oh wow you're fast.

**Comment by dbp** [comment]
:)

**Comment by emhoracek** [comment]
Yep, that works! Thanks

**Comment by dbp** [comment]
Do you want to fix or should I?

**Comment by emhoracek** [comment]
I fixed it.

**Comment by dbp** [comment]
Thanks!
