### ISSUE TITLE
Dealing with non-string custom JSON fields

### ISSUE THREAD

**Issue by emhoracek** [positiondev/offset#21]
For example,  `{ sticky: true }`. This doesn't seem to work right now?

**Comment by dbp** [comment]
Hmm. Ooops! Does it turn that into a string `"true"` or does it explode? Turning things into a string could be a quick fix; though it would probably be better to allow booleans / numbers in the same way that text is currently...

**Comment by emhoracek** [comment]
According to Eli, it's just blank? Haven't tried out any simple test cases yet.

**Comment by emhoracek** [comment]
I think this was a misunderstanding. It creates "true" as a string, not `True`, but it works fine.
