### ISSUE TITLE
Add RSS feeds

### ISSUE THREAD

**Issue by dbp** [positiondev/offset#9]

**Comment by emhoracek** [comment]
@dbp Nathan said that some CA readers were asking for this recently. Do you have any ideas what would be involved?

**Comment by dbp** [comment]
I actually don't think it'd be too hard - as RSS feeds are just XML with a particular format, and you should be able to do that with a normal larceny page... Then you have to set the proper content-type, and hopefully readers can understand? There are a couple different formats for RSS (Atom? Something else? etc), and not sure if there are better or worse ones, and whether the better ones are more involved, but I think it's pretty much an include-as-much-as-you-want format, so at least getting a basic version should be straightforward for someone familiar with offset / larceny :)

**Comment by emhoracek** [comment]
@dbp I've never used RSS so I wasn't sure, but that's what I hoped, yay! Thanks for the help!

**Comment by dbp** [comment]
Yeah, I always thought the "feed" part meant that there was something fancy, but it is really just a machine-readable index page that gets polled periodically :)

**Comment by emhoracek** [comment]
Lots of room for improvement but basic feeds are done.
